// system_on_chip.v

// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module system_on_chip (
		input  wire [3:0]  button_export,      //      button.export
		input  wire        clk_clk,            //         clk.clk
		output wire [31:0] id7_segment_export, // id7_segment.export
		output wire [12:0] memory_mem_a,       //      memory.mem_a
		output wire [2:0]  memory_mem_ba,      //            .mem_ba
		output wire        memory_mem_ck,      //            .mem_ck
		output wire        memory_mem_ck_n,    //            .mem_ck_n
		output wire        memory_mem_cke,     //            .mem_cke
		output wire        memory_mem_cs_n,    //            .mem_cs_n
		output wire        memory_mem_ras_n,   //            .mem_ras_n
		output wire        memory_mem_cas_n,   //            .mem_cas_n
		output wire        memory_mem_we_n,    //            .mem_we_n
		output wire        memory_mem_reset_n, //            .mem_reset_n
		inout  wire [7:0]  memory_mem_dq,      //            .mem_dq
		inout  wire        memory_mem_dqs,     //            .mem_dqs
		inout  wire        memory_mem_dqs_n,   //            .mem_dqs_n
		output wire        memory_mem_odt,     //            .mem_odt
		output wire        memory_mem_dm,      //            .mem_dm
		input  wire        memory_oct_rzqin,   //            .oct_rzqin
		input  wire        reset_reset_n,      //       reset.reset_n
		input  wire [7:0]  switches_export     //    switches.export
	);

	wire  [31:0] nios_data_master_readdata;                            // mm_interconnect_0:NIOS_data_master_readdata -> NIOS:d_readdata
	wire         nios_data_master_waitrequest;                         // mm_interconnect_0:NIOS_data_master_waitrequest -> NIOS:d_waitrequest
	wire         nios_data_master_debugaccess;                         // NIOS:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:NIOS_data_master_debugaccess
	wire  [13:0] nios_data_master_address;                             // NIOS:d_address -> mm_interconnect_0:NIOS_data_master_address
	wire   [3:0] nios_data_master_byteenable;                          // NIOS:d_byteenable -> mm_interconnect_0:NIOS_data_master_byteenable
	wire         nios_data_master_read;                                // NIOS:d_read -> mm_interconnect_0:NIOS_data_master_read
	wire         nios_data_master_write;                               // NIOS:d_write -> mm_interconnect_0:NIOS_data_master_write
	wire  [31:0] nios_data_master_writedata;                           // NIOS:d_writedata -> mm_interconnect_0:NIOS_data_master_writedata
	wire  [31:0] nios_instruction_master_readdata;                     // mm_interconnect_0:NIOS_instruction_master_readdata -> NIOS:i_readdata
	wire         nios_instruction_master_waitrequest;                  // mm_interconnect_0:NIOS_instruction_master_waitrequest -> NIOS:i_waitrequest
	wire  [13:0] nios_instruction_master_address;                      // NIOS:i_address -> mm_interconnect_0:NIOS_instruction_master_address
	wire         nios_instruction_master_read;                         // NIOS:i_read -> mm_interconnect_0:NIOS_instruction_master_read
	wire         mm_interconnect_0_uart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:UART_avalon_jtag_slave_chipselect -> UART:av_chipselect
	wire  [31:0] mm_interconnect_0_uart_avalon_jtag_slave_readdata;    // UART:av_readdata -> mm_interconnect_0:UART_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_uart_avalon_jtag_slave_waitrequest; // UART:av_waitrequest -> mm_interconnect_0:UART_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_uart_avalon_jtag_slave_address;     // mm_interconnect_0:UART_avalon_jtag_slave_address -> UART:av_address
	wire         mm_interconnect_0_uart_avalon_jtag_slave_read;        // mm_interconnect_0:UART_avalon_jtag_slave_read -> UART:av_read_n
	wire         mm_interconnect_0_uart_avalon_jtag_slave_write;       // mm_interconnect_0:UART_avalon_jtag_slave_write -> UART:av_write_n
	wire  [31:0] mm_interconnect_0_uart_avalon_jtag_slave_writedata;   // mm_interconnect_0:UART_avalon_jtag_slave_writedata -> UART:av_writedata
	wire  [31:0] mm_interconnect_0_nios_debug_mem_slave_readdata;      // NIOS:debug_mem_slave_readdata -> mm_interconnect_0:NIOS_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios_debug_mem_slave_waitrequest;   // NIOS:debug_mem_slave_waitrequest -> mm_interconnect_0:NIOS_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios_debug_mem_slave_debugaccess;   // mm_interconnect_0:NIOS_debug_mem_slave_debugaccess -> NIOS:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios_debug_mem_slave_address;       // mm_interconnect_0:NIOS_debug_mem_slave_address -> NIOS:debug_mem_slave_address
	wire         mm_interconnect_0_nios_debug_mem_slave_read;          // mm_interconnect_0:NIOS_debug_mem_slave_read -> NIOS:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios_debug_mem_slave_byteenable;    // mm_interconnect_0:NIOS_debug_mem_slave_byteenable -> NIOS:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios_debug_mem_slave_write;         // mm_interconnect_0:NIOS_debug_mem_slave_write -> NIOS:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios_debug_mem_slave_writedata;     // mm_interconnect_0:NIOS_debug_mem_slave_writedata -> NIOS:debug_mem_slave_writedata
	wire         mm_interconnect_0_ram_s1_chipselect;                  // mm_interconnect_0:RAM_s1_chipselect -> RAM:chipselect
	wire  [31:0] mm_interconnect_0_ram_s1_readdata;                    // RAM:readdata -> mm_interconnect_0:RAM_s1_readdata
	wire  [10:0] mm_interconnect_0_ram_s1_address;                     // mm_interconnect_0:RAM_s1_address -> RAM:address
	wire   [3:0] mm_interconnect_0_ram_s1_byteenable;                  // mm_interconnect_0:RAM_s1_byteenable -> RAM:byteenable
	wire         mm_interconnect_0_ram_s1_write;                       // mm_interconnect_0:RAM_s1_write -> RAM:write
	wire  [31:0] mm_interconnect_0_ram_s1_writedata;                   // mm_interconnect_0:RAM_s1_writedata -> RAM:writedata
	wire         mm_interconnect_0_ram_s1_clken;                       // mm_interconnect_0:RAM_s1_clken -> RAM:clken
	wire         mm_interconnect_0_reg_7_segments_s1_chipselect;       // mm_interconnect_0:REG_7_SEGMENTS_s1_chipselect -> REG_7_SEGMENTS:chipselect
	wire  [31:0] mm_interconnect_0_reg_7_segments_s1_readdata;         // REG_7_SEGMENTS:readdata -> mm_interconnect_0:REG_7_SEGMENTS_s1_readdata
	wire   [1:0] mm_interconnect_0_reg_7_segments_s1_address;          // mm_interconnect_0:REG_7_SEGMENTS_s1_address -> REG_7_SEGMENTS:address
	wire         mm_interconnect_0_reg_7_segments_s1_write;            // mm_interconnect_0:REG_7_SEGMENTS_s1_write -> REG_7_SEGMENTS:write_n
	wire  [31:0] mm_interconnect_0_reg_7_segments_s1_writedata;        // mm_interconnect_0:REG_7_SEGMENTS_s1_writedata -> REG_7_SEGMENTS:writedata
	wire         mm_interconnect_0_reg_buttons_s1_chipselect;          // mm_interconnect_0:REG_BUTTONS_s1_chipselect -> REG_BUTTONS:chipselect
	wire  [31:0] mm_interconnect_0_reg_buttons_s1_readdata;            // REG_BUTTONS:readdata -> mm_interconnect_0:REG_BUTTONS_s1_readdata
	wire   [1:0] mm_interconnect_0_reg_buttons_s1_address;             // mm_interconnect_0:REG_BUTTONS_s1_address -> REG_BUTTONS:address
	wire         mm_interconnect_0_reg_buttons_s1_write;               // mm_interconnect_0:REG_BUTTONS_s1_write -> REG_BUTTONS:write_n
	wire  [31:0] mm_interconnect_0_reg_buttons_s1_writedata;           // mm_interconnect_0:REG_BUTTONS_s1_writedata -> REG_BUTTONS:writedata
	wire         mm_interconnect_0_timer_s1_chipselect;                // mm_interconnect_0:TIMER_s1_chipselect -> TIMER:chipselect
	wire  [15:0] mm_interconnect_0_timer_s1_readdata;                  // TIMER:readdata -> mm_interconnect_0:TIMER_s1_readdata
	wire   [2:0] mm_interconnect_0_timer_s1_address;                   // mm_interconnect_0:TIMER_s1_address -> TIMER:address
	wire         mm_interconnect_0_timer_s1_write;                     // mm_interconnect_0:TIMER_s1_write -> TIMER:write_n
	wire  [15:0] mm_interconnect_0_timer_s1_writedata;                 // mm_interconnect_0:TIMER_s1_writedata -> TIMER:writedata
	wire         mm_interconnect_0_reg_switches_s1_chipselect;         // mm_interconnect_0:REG_SWITCHES_s1_chipselect -> REG_SWITCHES:chipselect
	wire  [31:0] mm_interconnect_0_reg_switches_s1_readdata;           // REG_SWITCHES:readdata -> mm_interconnect_0:REG_SWITCHES_s1_readdata
	wire   [1:0] mm_interconnect_0_reg_switches_s1_address;            // mm_interconnect_0:REG_SWITCHES_s1_address -> REG_SWITCHES:address
	wire         mm_interconnect_0_reg_switches_s1_write;              // mm_interconnect_0:REG_SWITCHES_s1_write -> REG_SWITCHES:write_n
	wire  [31:0] mm_interconnect_0_reg_switches_s1_writedata;          // mm_interconnect_0:REG_SWITCHES_s1_writedata -> REG_SWITCHES:writedata
	wire  [31:0] mm_interconnect_0_fifo_out_readdata;                  // FIFO:avalonmm_read_slave_readdata -> mm_interconnect_0:FIFO_out_readdata
	wire         mm_interconnect_0_fifo_out_waitrequest;               // FIFO:avalonmm_read_slave_waitrequest -> mm_interconnect_0:FIFO_out_waitrequest
	wire         mm_interconnect_0_fifo_out_read;                      // mm_interconnect_0:FIFO_out_read -> FIFO:avalonmm_read_slave_read
	wire         irq_mapper_receiver0_irq;                             // TIMER:irq -> irq_mapper:receiver0_irq
	wire         irq_mapper_receiver1_irq;                             // UART:av_irq -> irq_mapper:receiver1_irq
	wire         irq_mapper_receiver2_irq;                             // REG_BUTTONS:irq -> irq_mapper:receiver2_irq
	wire  [31:0] nios_irq_irq;                                         // irq_mapper:sender_irq -> NIOS:irq
	wire         rst_controller_reset_out_reset;                       // rst_controller:reset_out -> [FIFO:reset_n, NIOS:reset_n, RAM:reset, REG_7_SEGMENTS:reset_n, REG_BUTTONS:reset_n, REG_SWITCHES:reset_n, TIMER:reset_n, UART:rst_n, irq_mapper:reset, mm_interconnect_0:NIOS_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                   // rst_controller:reset_req -> [NIOS:reset_req, RAM:reset_req, rst_translator:reset_req_in]

	system_on_chip_ARM #(
		.F2S_Width (2),
		.S2F_Width (2)
	) arm (
		.h2f_mpu_eventi     (),                   //    h2f_mpu_events.eventi
		.h2f_mpu_evento     (),                   //                  .evento
		.h2f_mpu_standbywfe (),                   //                  .standbywfe
		.h2f_mpu_standbywfi (),                   //                  .standbywfi
		.mem_a              (memory_mem_a),       //            memory.mem_a
		.mem_ba             (memory_mem_ba),      //                  .mem_ba
		.mem_ck             (memory_mem_ck),      //                  .mem_ck
		.mem_ck_n           (memory_mem_ck_n),    //                  .mem_ck_n
		.mem_cke            (memory_mem_cke),     //                  .mem_cke
		.mem_cs_n           (memory_mem_cs_n),    //                  .mem_cs_n
		.mem_ras_n          (memory_mem_ras_n),   //                  .mem_ras_n
		.mem_cas_n          (memory_mem_cas_n),   //                  .mem_cas_n
		.mem_we_n           (memory_mem_we_n),    //                  .mem_we_n
		.mem_reset_n        (memory_mem_reset_n), //                  .mem_reset_n
		.mem_dq             (memory_mem_dq),      //                  .mem_dq
		.mem_dqs            (memory_mem_dqs),     //                  .mem_dqs
		.mem_dqs_n          (memory_mem_dqs_n),   //                  .mem_dqs_n
		.mem_odt            (memory_mem_odt),     //                  .mem_odt
		.mem_dm             (memory_mem_dm),      //                  .mem_dm
		.oct_rzqin          (memory_oct_rzqin),   //                  .oct_rzqin
		.h2f_rst_n          (),                   //         h2f_reset.reset_n
		.f2h_sdram0_clk     (clk_clk),            //  f2h_sdram0_clock.clk
		.f2h_sdram0_ARADDR  (),                   //   f2h_sdram0_data.araddr
		.f2h_sdram0_ARLEN   (),                   //                  .arlen
		.f2h_sdram0_ARID    (),                   //                  .arid
		.f2h_sdram0_ARSIZE  (),                   //                  .arsize
		.f2h_sdram0_ARBURST (),                   //                  .arburst
		.f2h_sdram0_ARLOCK  (),                   //                  .arlock
		.f2h_sdram0_ARPROT  (),                   //                  .arprot
		.f2h_sdram0_ARVALID (),                   //                  .arvalid
		.f2h_sdram0_ARCACHE (),                   //                  .arcache
		.f2h_sdram0_AWADDR  (),                   //                  .awaddr
		.f2h_sdram0_AWLEN   (),                   //                  .awlen
		.f2h_sdram0_AWID    (),                   //                  .awid
		.f2h_sdram0_AWSIZE  (),                   //                  .awsize
		.f2h_sdram0_AWBURST (),                   //                  .awburst
		.f2h_sdram0_AWLOCK  (),                   //                  .awlock
		.f2h_sdram0_AWPROT  (),                   //                  .awprot
		.f2h_sdram0_AWVALID (),                   //                  .awvalid
		.f2h_sdram0_AWCACHE (),                   //                  .awcache
		.f2h_sdram0_BRESP   (),                   //                  .bresp
		.f2h_sdram0_BID     (),                   //                  .bid
		.f2h_sdram0_BVALID  (),                   //                  .bvalid
		.f2h_sdram0_BREADY  (),                   //                  .bready
		.f2h_sdram0_ARREADY (),                   //                  .arready
		.f2h_sdram0_AWREADY (),                   //                  .awready
		.f2h_sdram0_RREADY  (),                   //                  .rready
		.f2h_sdram0_RDATA   (),                   //                  .rdata
		.f2h_sdram0_RRESP   (),                   //                  .rresp
		.f2h_sdram0_RLAST   (),                   //                  .rlast
		.f2h_sdram0_RID     (),                   //                  .rid
		.f2h_sdram0_RVALID  (),                   //                  .rvalid
		.f2h_sdram0_WLAST   (),                   //                  .wlast
		.f2h_sdram0_WVALID  (),                   //                  .wvalid
		.f2h_sdram0_WDATA   (),                   //                  .wdata
		.f2h_sdram0_WSTRB   (),                   //                  .wstrb
		.f2h_sdram0_WREADY  (),                   //                  .wready
		.f2h_sdram0_WID     (),                   //                  .wid
		.h2f_axi_clk        (clk_clk),            //     h2f_axi_clock.clk
		.h2f_AWID           (),                   //    h2f_axi_master.awid
		.h2f_AWADDR         (),                   //                  .awaddr
		.h2f_AWLEN          (),                   //                  .awlen
		.h2f_AWSIZE         (),                   //                  .awsize
		.h2f_AWBURST        (),                   //                  .awburst
		.h2f_AWLOCK         (),                   //                  .awlock
		.h2f_AWCACHE        (),                   //                  .awcache
		.h2f_AWPROT         (),                   //                  .awprot
		.h2f_AWVALID        (),                   //                  .awvalid
		.h2f_AWREADY        (),                   //                  .awready
		.h2f_WID            (),                   //                  .wid
		.h2f_WDATA          (),                   //                  .wdata
		.h2f_WSTRB          (),                   //                  .wstrb
		.h2f_WLAST          (),                   //                  .wlast
		.h2f_WVALID         (),                   //                  .wvalid
		.h2f_WREADY         (),                   //                  .wready
		.h2f_BID            (),                   //                  .bid
		.h2f_BRESP          (),                   //                  .bresp
		.h2f_BVALID         (),                   //                  .bvalid
		.h2f_BREADY         (),                   //                  .bready
		.h2f_ARID           (),                   //                  .arid
		.h2f_ARADDR         (),                   //                  .araddr
		.h2f_ARLEN          (),                   //                  .arlen
		.h2f_ARSIZE         (),                   //                  .arsize
		.h2f_ARBURST        (),                   //                  .arburst
		.h2f_ARLOCK         (),                   //                  .arlock
		.h2f_ARCACHE        (),                   //                  .arcache
		.h2f_ARPROT         (),                   //                  .arprot
		.h2f_ARVALID        (),                   //                  .arvalid
		.h2f_ARREADY        (),                   //                  .arready
		.h2f_RID            (),                   //                  .rid
		.h2f_RDATA          (),                   //                  .rdata
		.h2f_RRESP          (),                   //                  .rresp
		.h2f_RLAST          (),                   //                  .rlast
		.h2f_RVALID         (),                   //                  .rvalid
		.h2f_RREADY         (),                   //                  .rready
		.f2h_axi_clk        (clk_clk),            //     f2h_axi_clock.clk
		.f2h_AWID           (),                   //     f2h_axi_slave.awid
		.f2h_AWADDR         (),                   //                  .awaddr
		.f2h_AWLEN          (),                   //                  .awlen
		.f2h_AWSIZE         (),                   //                  .awsize
		.f2h_AWBURST        (),                   //                  .awburst
		.f2h_AWLOCK         (),                   //                  .awlock
		.f2h_AWCACHE        (),                   //                  .awcache
		.f2h_AWPROT         (),                   //                  .awprot
		.f2h_AWVALID        (),                   //                  .awvalid
		.f2h_AWREADY        (),                   //                  .awready
		.f2h_AWUSER         (),                   //                  .awuser
		.f2h_WID            (),                   //                  .wid
		.f2h_WDATA          (),                   //                  .wdata
		.f2h_WSTRB          (),                   //                  .wstrb
		.f2h_WLAST          (),                   //                  .wlast
		.f2h_WVALID         (),                   //                  .wvalid
		.f2h_WREADY         (),                   //                  .wready
		.f2h_BID            (),                   //                  .bid
		.f2h_BRESP          (),                   //                  .bresp
		.f2h_BVALID         (),                   //                  .bvalid
		.f2h_BREADY         (),                   //                  .bready
		.f2h_ARID           (),                   //                  .arid
		.f2h_ARADDR         (),                   //                  .araddr
		.f2h_ARLEN          (),                   //                  .arlen
		.f2h_ARSIZE         (),                   //                  .arsize
		.f2h_ARBURST        (),                   //                  .arburst
		.f2h_ARLOCK         (),                   //                  .arlock
		.f2h_ARCACHE        (),                   //                  .arcache
		.f2h_ARPROT         (),                   //                  .arprot
		.f2h_ARVALID        (),                   //                  .arvalid
		.f2h_ARREADY        (),                   //                  .arready
		.f2h_ARUSER         (),                   //                  .aruser
		.f2h_RID            (),                   //                  .rid
		.f2h_RDATA          (),                   //                  .rdata
		.f2h_RRESP          (),                   //                  .rresp
		.f2h_RLAST          (),                   //                  .rlast
		.f2h_RVALID         (),                   //                  .rvalid
		.f2h_RREADY         (),                   //                  .rready
		.h2f_lw_axi_clk     (clk_clk),            //  h2f_lw_axi_clock.clk
		.h2f_lw_AWID        (),                   // h2f_lw_axi_master.awid
		.h2f_lw_AWADDR      (),                   //                  .awaddr
		.h2f_lw_AWLEN       (),                   //                  .awlen
		.h2f_lw_AWSIZE      (),                   //                  .awsize
		.h2f_lw_AWBURST     (),                   //                  .awburst
		.h2f_lw_AWLOCK      (),                   //                  .awlock
		.h2f_lw_AWCACHE     (),                   //                  .awcache
		.h2f_lw_AWPROT      (),                   //                  .awprot
		.h2f_lw_AWVALID     (),                   //                  .awvalid
		.h2f_lw_AWREADY     (),                   //                  .awready
		.h2f_lw_WID         (),                   //                  .wid
		.h2f_lw_WDATA       (),                   //                  .wdata
		.h2f_lw_WSTRB       (),                   //                  .wstrb
		.h2f_lw_WLAST       (),                   //                  .wlast
		.h2f_lw_WVALID      (),                   //                  .wvalid
		.h2f_lw_WREADY      (),                   //                  .wready
		.h2f_lw_BID         (),                   //                  .bid
		.h2f_lw_BRESP       (),                   //                  .bresp
		.h2f_lw_BVALID      (),                   //                  .bvalid
		.h2f_lw_BREADY      (),                   //                  .bready
		.h2f_lw_ARID        (),                   //                  .arid
		.h2f_lw_ARADDR      (),                   //                  .araddr
		.h2f_lw_ARLEN       (),                   //                  .arlen
		.h2f_lw_ARSIZE      (),                   //                  .arsize
		.h2f_lw_ARBURST     (),                   //                  .arburst
		.h2f_lw_ARLOCK      (),                   //                  .arlock
		.h2f_lw_ARCACHE     (),                   //                  .arcache
		.h2f_lw_ARPROT      (),                   //                  .arprot
		.h2f_lw_ARVALID     (),                   //                  .arvalid
		.h2f_lw_ARREADY     (),                   //                  .arready
		.h2f_lw_RID         (),                   //                  .rid
		.h2f_lw_RDATA       (),                   //                  .rdata
		.h2f_lw_RRESP       (),                   //                  .rresp
		.h2f_lw_RLAST       (),                   //                  .rlast
		.h2f_lw_RVALID      (),                   //                  .rvalid
		.h2f_lw_RREADY      ()                    //                  .rready
	);

	system_on_chip_FIFO fifo (
		.wrclock                          (clk_clk),                                //   clk_in.clk
		.reset_n                          (~rst_controller_reset_out_reset),        // reset_in.reset_n
		.avalonmm_write_slave_writedata   (),                                       //       in.writedata
		.avalonmm_write_slave_write       (),                                       //         .write
		.avalonmm_write_slave_waitrequest (),                                       //         .waitrequest
		.avalonmm_read_slave_readdata     (mm_interconnect_0_fifo_out_readdata),    //      out.readdata
		.avalonmm_read_slave_read         (mm_interconnect_0_fifo_out_read),        //         .read
		.avalonmm_read_slave_waitrequest  (mm_interconnect_0_fifo_out_waitrequest), //         .waitrequest
		.wrclk_control_slave_address      (),                                       //   in_csr.address
		.wrclk_control_slave_read         (),                                       //         .read
		.wrclk_control_slave_writedata    (),                                       //         .writedata
		.wrclk_control_slave_write        (),                                       //         .write
		.wrclk_control_slave_readdata     (),                                       //         .readdata
		.wrclk_control_slave_irq          ()                                        //   in_irq.irq
	);

	system_on_chip_NIOS nios (
		.clk                                 (clk_clk),                                            //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                    //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                 //                          .reset_req
		.d_address                           (nios_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios_data_master_read),                              //                          .read
		.d_readdata                          (nios_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios_data_master_write),                             //                          .write
		.d_writedata                         (nios_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (nios_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios_instruction_master_read),                       //                          .read
		.i_readdata                          (nios_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (nios_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (),                                                   //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                    // custom_instruction_master.readra
	);

	system_on_chip_RAM ram (
		.clk        (clk_clk),                             //   clk1.clk
		.address    (mm_interconnect_0_ram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_ram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_ram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_ram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_ram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_ram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_ram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),      // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),  //       .reset_req
		.freeze     (1'b0)                                 // (terminated)
	);

	system_on_chip_REG_7_SEGMENTS reg_7_segments (
		.clk        (clk_clk),                                        //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                //               reset.reset_n
		.address    (mm_interconnect_0_reg_7_segments_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_reg_7_segments_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_reg_7_segments_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_reg_7_segments_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_reg_7_segments_s1_readdata),   //                    .readdata
		.out_port   (id7_segment_export)                              // external_connection.export
	);

	system_on_chip_REG_BUTTONS reg_buttons (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_reg_buttons_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_reg_buttons_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_reg_buttons_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_reg_buttons_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_reg_buttons_s1_readdata),   //                    .readdata
		.in_port    (button_export),                               // external_connection.export
		.irq        (irq_mapper_receiver2_irq)                     //                 irq.irq
	);

	system_on_chip_REG_SWITCHES reg_switches (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_reg_switches_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_reg_switches_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_reg_switches_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_reg_switches_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_reg_switches_s1_readdata),   //                    .readdata
		.in_port    (switches_export),                              // external_connection.export
		.irq        ()                                              //                 irq.irq
	);

	system_on_chip_TIMER timer (
		.clk        (clk_clk),                               //   clk.clk
		.reset_n    (~rst_controller_reset_out_reset),       // reset.reset_n
		.address    (mm_interconnect_0_timer_s1_address),    //    s1.address
		.writedata  (mm_interconnect_0_timer_s1_writedata),  //      .writedata
		.readdata   (mm_interconnect_0_timer_s1_readdata),   //      .readdata
		.chipselect (mm_interconnect_0_timer_s1_chipselect), //      .chipselect
		.write_n    (~mm_interconnect_0_timer_s1_write),     //      .write_n
		.irq        (irq_mapper_receiver0_irq)               //   irq.irq
	);

	system_on_chip_UART uart (
		.clk            (clk_clk),                                              //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                      //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver1_irq)                              //               irq.irq
	);

	system_on_chip_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                          (clk_clk),                                              //                        clk_0_clk.clk
		.NIOS_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                       // NIOS_reset_reset_bridge_in_reset.reset
		.NIOS_data_master_address               (nios_data_master_address),                             //                 NIOS_data_master.address
		.NIOS_data_master_waitrequest           (nios_data_master_waitrequest),                         //                                 .waitrequest
		.NIOS_data_master_byteenable            (nios_data_master_byteenable),                          //                                 .byteenable
		.NIOS_data_master_read                  (nios_data_master_read),                                //                                 .read
		.NIOS_data_master_readdata              (nios_data_master_readdata),                            //                                 .readdata
		.NIOS_data_master_write                 (nios_data_master_write),                               //                                 .write
		.NIOS_data_master_writedata             (nios_data_master_writedata),                           //                                 .writedata
		.NIOS_data_master_debugaccess           (nios_data_master_debugaccess),                         //                                 .debugaccess
		.NIOS_instruction_master_address        (nios_instruction_master_address),                      //          NIOS_instruction_master.address
		.NIOS_instruction_master_waitrequest    (nios_instruction_master_waitrequest),                  //                                 .waitrequest
		.NIOS_instruction_master_read           (nios_instruction_master_read),                         //                                 .read
		.NIOS_instruction_master_readdata       (nios_instruction_master_readdata),                     //                                 .readdata
		.FIFO_out_read                          (mm_interconnect_0_fifo_out_read),                      //                         FIFO_out.read
		.FIFO_out_readdata                      (mm_interconnect_0_fifo_out_readdata),                  //                                 .readdata
		.FIFO_out_waitrequest                   (mm_interconnect_0_fifo_out_waitrequest),               //                                 .waitrequest
		.NIOS_debug_mem_slave_address           (mm_interconnect_0_nios_debug_mem_slave_address),       //             NIOS_debug_mem_slave.address
		.NIOS_debug_mem_slave_write             (mm_interconnect_0_nios_debug_mem_slave_write),         //                                 .write
		.NIOS_debug_mem_slave_read              (mm_interconnect_0_nios_debug_mem_slave_read),          //                                 .read
		.NIOS_debug_mem_slave_readdata          (mm_interconnect_0_nios_debug_mem_slave_readdata),      //                                 .readdata
		.NIOS_debug_mem_slave_writedata         (mm_interconnect_0_nios_debug_mem_slave_writedata),     //                                 .writedata
		.NIOS_debug_mem_slave_byteenable        (mm_interconnect_0_nios_debug_mem_slave_byteenable),    //                                 .byteenable
		.NIOS_debug_mem_slave_waitrequest       (mm_interconnect_0_nios_debug_mem_slave_waitrequest),   //                                 .waitrequest
		.NIOS_debug_mem_slave_debugaccess       (mm_interconnect_0_nios_debug_mem_slave_debugaccess),   //                                 .debugaccess
		.RAM_s1_address                         (mm_interconnect_0_ram_s1_address),                     //                           RAM_s1.address
		.RAM_s1_write                           (mm_interconnect_0_ram_s1_write),                       //                                 .write
		.RAM_s1_readdata                        (mm_interconnect_0_ram_s1_readdata),                    //                                 .readdata
		.RAM_s1_writedata                       (mm_interconnect_0_ram_s1_writedata),                   //                                 .writedata
		.RAM_s1_byteenable                      (mm_interconnect_0_ram_s1_byteenable),                  //                                 .byteenable
		.RAM_s1_chipselect                      (mm_interconnect_0_ram_s1_chipselect),                  //                                 .chipselect
		.RAM_s1_clken                           (mm_interconnect_0_ram_s1_clken),                       //                                 .clken
		.REG_7_SEGMENTS_s1_address              (mm_interconnect_0_reg_7_segments_s1_address),          //                REG_7_SEGMENTS_s1.address
		.REG_7_SEGMENTS_s1_write                (mm_interconnect_0_reg_7_segments_s1_write),            //                                 .write
		.REG_7_SEGMENTS_s1_readdata             (mm_interconnect_0_reg_7_segments_s1_readdata),         //                                 .readdata
		.REG_7_SEGMENTS_s1_writedata            (mm_interconnect_0_reg_7_segments_s1_writedata),        //                                 .writedata
		.REG_7_SEGMENTS_s1_chipselect           (mm_interconnect_0_reg_7_segments_s1_chipselect),       //                                 .chipselect
		.REG_BUTTONS_s1_address                 (mm_interconnect_0_reg_buttons_s1_address),             //                   REG_BUTTONS_s1.address
		.REG_BUTTONS_s1_write                   (mm_interconnect_0_reg_buttons_s1_write),               //                                 .write
		.REG_BUTTONS_s1_readdata                (mm_interconnect_0_reg_buttons_s1_readdata),            //                                 .readdata
		.REG_BUTTONS_s1_writedata               (mm_interconnect_0_reg_buttons_s1_writedata),           //                                 .writedata
		.REG_BUTTONS_s1_chipselect              (mm_interconnect_0_reg_buttons_s1_chipselect),          //                                 .chipselect
		.REG_SWITCHES_s1_address                (mm_interconnect_0_reg_switches_s1_address),            //                  REG_SWITCHES_s1.address
		.REG_SWITCHES_s1_write                  (mm_interconnect_0_reg_switches_s1_write),              //                                 .write
		.REG_SWITCHES_s1_readdata               (mm_interconnect_0_reg_switches_s1_readdata),           //                                 .readdata
		.REG_SWITCHES_s1_writedata              (mm_interconnect_0_reg_switches_s1_writedata),          //                                 .writedata
		.REG_SWITCHES_s1_chipselect             (mm_interconnect_0_reg_switches_s1_chipselect),         //                                 .chipselect
		.TIMER_s1_address                       (mm_interconnect_0_timer_s1_address),                   //                         TIMER_s1.address
		.TIMER_s1_write                         (mm_interconnect_0_timer_s1_write),                     //                                 .write
		.TIMER_s1_readdata                      (mm_interconnect_0_timer_s1_readdata),                  //                                 .readdata
		.TIMER_s1_writedata                     (mm_interconnect_0_timer_s1_writedata),                 //                                 .writedata
		.TIMER_s1_chipselect                    (mm_interconnect_0_timer_s1_chipselect),                //                                 .chipselect
		.UART_avalon_jtag_slave_address         (mm_interconnect_0_uart_avalon_jtag_slave_address),     //           UART_avalon_jtag_slave.address
		.UART_avalon_jtag_slave_write           (mm_interconnect_0_uart_avalon_jtag_slave_write),       //                                 .write
		.UART_avalon_jtag_slave_read            (mm_interconnect_0_uart_avalon_jtag_slave_read),        //                                 .read
		.UART_avalon_jtag_slave_readdata        (mm_interconnect_0_uart_avalon_jtag_slave_readdata),    //                                 .readdata
		.UART_avalon_jtag_slave_writedata       (mm_interconnect_0_uart_avalon_jtag_slave_writedata),   //                                 .writedata
		.UART_avalon_jtag_slave_waitrequest     (mm_interconnect_0_uart_avalon_jtag_slave_waitrequest), //                                 .waitrequest
		.UART_avalon_jtag_slave_chipselect      (mm_interconnect_0_uart_avalon_jtag_slave_chipselect)   //                                 .chipselect
	);

	system_on_chip_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),       // receiver1.irq
		.receiver2_irq (irq_mapper_receiver2_irq),       // receiver2.irq
		.sender_irq    (nios_irq_irq)                    //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
